---
deployment:
  tasks:
    - /bin/mkdir -p /home/adatechn/servis-takip-panel/database
    - /bin/mkdir -p /home/adatechn/servis-takip-panel/downloads
    - /bin/chmod 755 /home/adatechn/servis-takip-panel/database
    - /bin/chmod 755 /home/adatechn/servis-takip-panel/downloads
